USE master;
CREATE DATABASE SignCPA;
DROP TABLE [Sign]
CREATE TABLE [Sign] (
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
SignTime DATETIME NOT NULL,
DoneLevel INT NOT NULL,
Content VARCHAR(MAX),
CreateTime DATETIME NOT NULL,
ModifyTime DATETIME NOT NULL,
Color VARCHAR(50) NOT NULL
)




